### ISSUE TITLE
Ability to insert a WidgetSpan in a StyledText

### ISSUE THREAD

**Issue by apalala-dev** [andyduke/styled_text_package#28]
This package is very usefull, especially for internationalization, however I have an use case where I can't use it : WidgetSpans.

I was using RichText (without translations) before and I added a sort of Chip with an avatar and a name in a WidgetSpan.

I didn't find a way to use StyledText with WidgetSpan but that would be really cool !

Is there a way that I missed ?

**Comment by andyduke** [comment]
@Kobatsu Now there is no such possibility. In the near future I will think about how this could be done.

**Comment by apalala-dev** [comment]
I made a PR ( #29 ) since I had an idea on how this could be achieved. It might not be perfect but could be a base for this !

**Comment by Zabadam** [comment]
> I made a PR ( #29 ) since I had an idea on how this could be achieved. It might not be perfect but could be a base for this !

I think this a great proposal!

**Comment by apalala-dev** [comment]
If you want to experiment with it, you can add it to your pubspec.yaml :

  ```
styled_text: #^2.0.0-nullsafety.0
    git:
      url: https://github.com/Kobatsu/styled_text_package.git
      path: styled_text/
```

I am using it in my own projet but I don't have enough users / tests on it to be sure it's free of bugs.
